spring:
  datasource:
    url: jdbc:mysql://192.168.0.149:3306/anti_fan?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC #mysql的内网地址不走流量
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver